name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
            python-version: ['3.x']

        steps:
          - uses: actions/checkout@v2
          - name: Setup python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
              architecture: x64
          - name: Install
            run: |
              python -m pip install --upgrade pip
              pip install .
              pip install flake8 pytest
          - name: Lint
            run: |
              flake8 . --show-source
